name: Execute Application
on: workflow_dispatch
jobs:
  Execute-Application:
    runs-on: [ubuntu-latest, windows-latest]
    environment: dev
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Resume and Cover Letter
        env:
          GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          EMAIL: ${{ secrets.EMAIL }}
        run: python3.12 ./src/main.py

      - name: Save Resume and Cover Letter to Directory on Linux
        if: runner.os == 'Linux'
        run: bash ./store_resume_and_cl.sh "hi" "hello"

      - name: Save Resume and Cover Letter to Directory on Windows
        if: runner.os == 'Windows'
        run: store_resume_and_cl.bat "hi" "hello"

      - name: Write to master CSV file
        run: python3.12 save_to_csv.py "hi" "hello"
            
